# Generated by Django 4.0.2 on 2022-02-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heis', '0008_alter_page_title'),
        ('recommendations', '0009_criterion_new21_guideline_new21'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_failures', models.IntegerField(default=1)),
                ('criterion', models.ManyToManyField(to='recommendations.Criterion')),
                ('page', models.ManyToManyField(to='heis.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('web_address', models.URLField(unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReviewAutomated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reviewed', models.DateField()),
                ('failure', models.ManyToManyField(to='reviews.Failure')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heis.institution')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.tool')),
            ],
            options={
                'verbose_name': 'Automated Review',
                'verbose_name_plural': 'Automated Reviews',
                'ordering': ('date_reviewed',),
            },
        ),
    ]
