# Generated by Django 4.0.2 on 2022-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_criterion_new21_guideline_new21'),
        ('heis', '0008_alter_page_title'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewautomated',
            name='failure',
        ),
        migrations.AddField(
            model_name='reviewautomated',
            name='criterion',
            field=models.ManyToManyField(to='recommendations.Criterion'),
        ),
        migrations.AddField(
            model_name='reviewautomated',
            name='page',
            field=models.ManyToManyField(to='heis.Page'),
        ),
        migrations.AddField(
            model_name='reviewautomated',
            name='total_failures',
            field=models.IntegerField(default=1),
        ),
    ]
