# Generated by Django 4.0.2 on 2022-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='principle',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
