# Generated by Django 4.0.2 on 2022-02-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_criterion_description_guideline_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='principle',
            name='description',
            field=models.TextField(),
        ),
    ]
