# Generated by Django 4.0.2 on 2022-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_criterion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='level',
            field=models.CharField(choices=[('1', 'A'), ('2', 'AA'), ('3', 'AAA')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='principle',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
