# Generated by Django 4.0.2 on 2022-02-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_alter_criterion_options_alter_guideline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ('guideline', 'criteria_id'), 'verbose_name_plural': 'Criteria'},
        ),
        migrations.AlterModelOptions(
            name='guideline',
            options={'ordering': ('principle', 'guideline_id')},
        ),
        migrations.AlterField(
            model_name='criterion',
            name='criteria_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='guideline_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='principle_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
