# Generated by Django 4.0.2 on 2022-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_alter_criterion_options_alter_guideline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='new21',
            field=models.BooleanField(default=False, verbose_name='New to WCAG 2.1?'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='new21',
            field=models.BooleanField(default=False, verbose_name='New to WCAG 2.1?'),
        ),
    ]
