# Generated by Django 4.0.2 on 2022-02-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('public', models.BooleanField(default=True)),
                ('non_profit', models.BooleanField(default=True, verbose_name='Non-profit')),
                ('university', models.BooleanField(default=True, help_text='An institution is considered a university if it offers both undergraduate and graduate programs.')),
                ('two_year', models.BooleanField(default=False, verbose_name='Two year')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('web_address', models.URLField(unique=True)),
                ('home_page', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heis.institution')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heis.region'),
        ),
    ]
