# Generated by Django 4.0.2 on 2022-02-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='community_college',
            field=models.BooleanField(default=False, help_text='True if the institution belongs to the Colorado Community College System (CCCS)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='votech',
            field=models.BooleanField(default=False, verbose_name='Technical or Vocational College or Institution'),
        ),
    ]
