# Generated by Django 4.0.2 on 2022-02-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heis', '0003_remove_institution_two_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AlterField(
            model_name='institution',
            name='community_college',
            field=models.BooleanField(default=False, help_text='True if the institution belongs to the Colorado Community College System (CCCS) or has Community College in its name.'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='university',
            field=models.BooleanField(default=True, help_text='An institution is considered a university if it offers several undergraduate and graduate programs.'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heis.city'),
        ),
    ]
