# Generated by Django 4.0.2 on 2022-02-07 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heis', '0004_city_alter_institution_community_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='region',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heis.region'),
        ),
    ]
