# Generated by Django 4.0.2 on 2022-02-07 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heis', '0005_remove_institution_city_remove_institution_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heis.city'),
        ),
    ]
