# Generated by Django 4.0.2 on 2022-02-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis', '0007_alter_city_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
